CREATE TABLE RECORDED_ROOM_TEMPERATURE (
TEMPERATURE_CELSIUS DOUBLE PRECISION NOT NULL,
TEMPERATURE_FAHRENHEIT DOUBLE PRECISION NOT NULL,
TEMPERATURE_DATE DATE NOT NULL,
TEMPERATURE_TIME TIME NOT NULL
);